Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'Facebook', :icon => 'fa-facebook')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'Twitter', :icon => 'fa-twitter')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'Google Plus', :icon => 'fa-google-plus')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'LinkedIn', :icon => 'fa-linkedin')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'Tumblr', :icon => 'fa-tumblr')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'SlideShare', :icon => 'fa-slideshare')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'VKontakte', :icon => 'fa-vk')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'Youtube', :icon => 'fa-youtube')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'Pinterest', :icon => 'fa-pinterest-p')
Blogging::BlogAdmin::SocialPage.find_or_create_by(:name => 'Dropbox', :icon => 'fa-dropbox')