Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'social_page', :content => 'html = "<div class=\'social-icons\'>"
 Blogging::BlogAdmin::SocialPage.all.each do |sp|
    html << "<a href=\'#{sp.url}\' class=\'social-icons__container\'> <i class=\'fa #{sp.icon}\'> </i>  </a>"
 end
return html << "</div>"', :attr_type => 'rb')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'navigation_widget', :content => 'html = "<ul class=\'blog-navigation\'> <li> <a href=\'/\'> Home </a> </li> "
Blogging::BlogAdmin::Page.all.each do |page|
   html <<  "<li> <a href=\'#{page.slug}\'> #{page.menu} </a> </li>"
end
return html << "</ul>"', :attr_type => 'rb')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'twitter_feed', :content => '<a class="twitter-timeline"  href="https://twitter.com/zikoku07" data-widget-id="635801868828999680">Tweets by @zikoku07 </a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?"http":"https";if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>', :attr_type => 'html')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'facebook_adds', :content => '<div id="likebox-wrapper">          <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fdropresumenow&amp;width&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false&amp;appId=1456591877929410">          </iframe>        </div>', :attr_type => 'html')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'top_banner_add', :content => '<a href="http://themeforest.net/user/ProteusThemes/portfolio?ref=ProteusThemes">            <img src="http://dummyimage.com/800x600&text=Your Add Here" class="img-responsive">          </a>', :attr_type => 'html')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'google_map', :content => '<div id="map"></div><script>var map;function initMap() {  map = new google.maps.Map(document.getElementById("map"), {    center: {lat: 23.709921, lng: 90.407143},    zoom: 8  });}</script><script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async defer></script>', :attr_type => 'html')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'contact_form', :content => '<div class="col-lg-8 col-lg-offset-2">    <form id="contact_form" action="/blogs/contact_us" method="POST" enctype="multipart/form-data" class="form-group">	<div class="row form-group">		<label for="name">Your name:</label>		<input id="name" class="input form-control" name="name" type="text" value=""  />	</div>	<div class="row form-group">		<label for="email">Your email:</label>		<input id="email" class="input  form-control" name="email" type="text" value="" size="30" />	</div>	<div class="row form-group">		<label for="message">Your message:</label><br /> <textarea id="message" class="input form-control" name="message" cols="30"></textarea>	</div> <div class="form-group clearfix"> <input id="submit_button" type="submit" value="Send email" class="btn btn-default pull-right"/>        </div>   </form></div>		', :attr_type => 'html')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'subscribe', :content => '<div> <section class="subscribe">    <div class="subscribe-pitch">      <h3>Subscribe</h3>      <p>Subscribe to our newsletter to get the latest scoop right to your inbox.<p>    </div>    <form action="news_letter" method="post" class="subscribe-form" data-remote="true"> <div class="input-group"> <input type="email" name="email" placeholder="Email" class="form-control"> <span class="input-group-btn"> <button type="submit" class="btn btn-default"> <i class="fa fa-check"> </i> </button>          </span>        </div>    </form>  </section></div>', :attr_type => 'html')
Blogging::BlogAdmin::Widget.find_or_create_by(:name => 'contact_us', :content => 'html = "For any information or feedback please contact us with"
html << "<a href=\'#{Blogging.blog_email}\'> #{Blogging.blog_email} </a>"', :attr_type => 'rb')